In [21]:
import pandas as pd
import json
import re

In [22]:
run_name = "make_model_union"


# load JSONL
records = []
with open("../aircraft_er_predictions/" + run_name + "_predictions_all.tsv") as f:
    for line in f:
        records.append(json.loads(line))

In [23]:
df = pd.DataFrame(records)
df.head()

,left,right,match,match_confidence
0,COL make VAL EMBRAER COL model VAL EMB135 COL ...,COL mfr VAL MITSUBISHI COL model VAL MU-2,0,0.999996
1,COL make VAL SIKORSKY COL model VAL S55 COL na...,COL mfr VAL CESSNA COL model VAL 421 Executive...,0,0.999996
2,COL make VAL PIPER COL model VAL PA60 COL name...,COL make VAL PIPER COL model VAL J2 COL series...,0,0.999996
3,COL make VAL CESSNA COL model VAL U3 COL cert ...,COL mfr VAL CESSNA COL model VAL AT-8 Bobcat C...,0,0.999996
4,COL make VAL GRUMMAN COL model VAL HU16 COL na...,COL mfr VAL SNOW COL model VAL S-2 COL code VA...,0,0.999996

In [24]:


gold = pd.read_csv("../data/ditto_aircraft/" + run_name + "/all_pairs_with_id.txt")
print(gold.head())

          left_id                     right_id  \
0  EMBRAER EMB135                     MU2 MU-2
1    SIKORSKY S55  C421 421 Executive Commuter
2      PIPER PA60                         7448
3       CESSNA U3              T50 AT-8 Bobcat
4    GRUMMAN HU16                     SS2P S-2

                                                left  \
0  COL make VAL EMBRAER COL model VAL EMB135 COL ...
1  COL make VAL SIKORSKY COL model VAL S55 COL na...
2  COL make VAL PIPER COL model VAL PA60 COL name...
3  COL make VAL CESSNA COL model VAL U3 COL cert ...
4  COL make VAL GRUMMAN COL model VAL HU16 COL na...

                                               right  label  \
0          COL mfr VAL MITSUBISHI COL model VAL MU-2      0
1  COL mfr VAL CESSNA COL model VAL 421 Executive...      0
2  COL make VAL PIPER COL model VAL J2 COL series...      0
3  COL mfr VAL CESSNA COL model VAL AT-8 Bobcat C...      0
4  COL mfr VAL SNOW COL model VAL S-2 COL code VA...      0

                source
0  doc8643_description
1  doc8643_description
2                cictt
3  doc8643_description
4  doc8643_description

In [25]:
df["gold"] = gold["label"]
df["left_id"] = gold["left_id"]
df["right_id"] = gold["right_id"]
df["source"] = gold["source"]

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_true = df["gold"]
y_pred = df["match"]

print("Accuracy:", accuracy_score(y_true, y_pred))
print("\nClassification report:\n", classification_report(y_true, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_true, y_pred))

Accuracy: 0.9987870039375137

Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    236021
           1       0.99      0.99      0.99     28613

    accuracy                           1.00    264634
   macro avg       1.00      1.00      1.00    264634
weighted avg       1.00      1.00      1.00    264634


Confusion matrix:
 [[235875    146]
 [   175  28438]]

In [37]:
errors = df[(df["gold"] != df["match"])]
errors

,left,right,match,match_confidence,gold,left_id,right_id,source
6384,COL make VAL GULFSTREAM COL model VAL GV COL c...,COL mfr VAL GULFSTREAM AEROSPACE COL model VAL...,0,0.706868,1,GULFSTREAM GV,GV-SP,reg
9587,COL make VAL CHAMPION COL model VAL 7KC COL na...,COL mfr VAL CHAMPION COL model VAL 7GCAA,1,0.473192,0,CHAMPION 7KC,CHAMP-7-GCAA,reg
13453,COL make VAL MONOCOUPE COL model VAL 90AL COL ...,COL mfr VAL MONOCOUPE COL model VAL 90,1,0.432130,0,MONOCOUPE 90AL,MONOCP-90,reg
13811,COL make VAL WACO COL model VAL INF COL cert V...,COL mfr VAL WACO COL model VAL KNF,1,0.458653,0,WACO INF,WACO-KNF-KNF,reg
17328,COL make VAL DIAMOND COL model VAL DV20 COL na...,COL mfr VAL DIAMOND COL model VAL DA-40 Katana...,1,0.999876,0,DIAMOND DV20,DA40 DA-40 Katana,doc8643_description
...,...,...,...,...,...,...,...,...
264020,COL make VAL TAYLORCRAFT COL model VAL BCS12 C...,COL make VAL TCRAFK COL model VAL BL COL serie...,1,0.530035,0,TAYLORCRAFT BCS12,TCRAFK-BL-S1265,faa
264181,COL make VAL EUROCOPTER COL model VAL EC155 CO...,COL mfr VAL KOREA AEROSPACE COL model VAL LAH,0,0.999996,1,EUROCOPTER EC155,EC55 LAH,doc8643_description
264183,COL make VAL WACO COL model VAL INF COL cert V...,COL mfr VAL WACO COL model VAL QCF,0,0.987778,1,WACO INF,WACF QCF,doc8643_description
264338,COL make VAL CONVAIR COL model VAL 440 COL nam...,COL mfr VAL CONVAIR COL model VAL 340,0,0.999995,1,CONVAIR 440,CV-440-5800STC,reg
264412,COL make VAL STEARMAN COL model VAL A75 COL na...,COL make VAL B COL model VAL 75 COL series VAL...,0,0.999996,1,STEARMAN A75,B-75-N2S4,faa

In [38]:
errors.to_csv('cictt_agg_repeat_errors.csv', index=False)

In [27]:
matches = df[(df["gold"] == 1) & (df["match"] == 1)]
matches

,left,right,match,match_confidence,gold,left_id,right_id,source
11,COL make VAL AGUSTA COL model VAL AW119 COL na...,COL mfr VAL AGUSTA COL model VAL A-119 Koala C...,1,0.999991,1,AGUSTA AW119,A119 A-119 Koala,doc8643_description
16,COL make VAL PARTENAVIA COL model VAL AP68 COL...,COL mfr VAL PARTENAVIA COL model VAL AP-68TP-3...,1,0.999991,1,PARTENAVIA AP68,P68T AP-68TP-300 Spartacus,doc8643_description
32,COL make VAL LEARJET COL model VAL 31 COL cert...,COL mfr VAL LEARJET COL model VAL 31,1,0.999985,1,LEARJET 31,LJ31 31,doc8643_description
66,COL make VAL BELLANCA COL model VAL 14 13 COL ...,COL mfr VAL NORTHERN COL model VAL 14 Cruisema...,1,0.999985,1,BELLANCA 14 13,B14A 14 Cruisemaster,doc8643_description
70,COL make VAL BOEING COL model VAL 737 COL name...,COL mfr VAL BOEING COL model VAL 737-401,1,0.999988,1,BOEING 737,B-737-401,reg
...,...,...,...,...,...,...,...,...
264603,COL make VAL CESSNA COL model VAL 525 COL name...,COL mfr VAL CESSNA COL model VAL 525C,1,0.999899,1,CESSNA 525,CE-525-525C,reg
264616,COL make VAL MORANE SAULNIER COL model VAL MS8...,COL mfr VAL PZL-OKECIE COL model VAL PZL-111 K...,1,0.999962,1,MORANE SAULNIER MS894,RALL PZL-111 Koliber Senior,doc8643_description
264622,COL make VAL AVIAN COL model VAL MAGNUM IX COL...,COL make VAL AVIAN COL model VAL MAGNUM COL se...,1,0.999987,1,AVIAN MAGNUM IX,AVIAN-MAGNUM-IX,faa
264623,COL make VAL EMBRAER COL model VAL EMB550 COL ...,COL code VAL E550,1,0.999986,1,EMBRAER EMB550,E550,doc8643_code
264628,COL make VAL EMBRAER COL model VAL EMB110 COL ...,COL mfr VAL EMBRAER COL model VAL SC-95 Bandei...,1,0.999991,1,EMBRAER EMB110,E110 SC-95 Bandeirante,doc8643_description

In [28]:
import re

PAIR_RE = re.compile(r"COL\s+(?P<key>.*?)\s+VAL\s+(?P<val>.*?)(?=\s+COL\s+|$)")

def record_to_kv_list(record: str):
    """Return list like ['make: WACO', 'model: EGC', ...] in original order."""
    s = str(record)
    return [f"{m.group('key').strip()}: {m.group('val').strip()}"
            for m in PAIR_RE.finditer(s)]

In [29]:
# assuming your dataframe is called matches and has columns "left" and "right"
matches["left_kv"]  = matches["left"].apply(record_to_kv_list)
matches["right_kv"] = matches["right"].apply(record_to_kv_list)

/tmp/ipykernel_103888/3629942744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["left_kv"]  = matches["left"].apply(record_to_kv_list)
/tmp/ipykernel_103888/3629942744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["right_kv"] = matches["right"].apply(record_to_kv_list)

In [30]:
matches.head()

,left,right,match,match_confidence,gold,left_id,right_id,source,left_kv,right_kv
11,COL make VAL AGUSTA COL model VAL AW119 COL na...,COL mfr VAL AGUSTA COL model VAL A-119 Koala C...,1,0.999991,1,AGUSTA AW119,A119 A-119 Koala,doc8643_description,"[make: AGUSTA, model: AW119, name: KOALA, cert...","[mfr: AGUSTA, model: A-119 Koala, code: A119]"
16,COL make VAL PARTENAVIA COL model VAL AP68 COL...,COL mfr VAL PARTENAVIA COL model VAL AP-68TP-3...,1,0.999991,1,PARTENAVIA AP68,P68T AP-68TP-300 Spartacus,doc8643_description,"[make: PARTENAVIA, model: AP68, name: SPARTACU...","[mfr: PARTENAVIA, model: AP-68TP-300 Spartacus]"
32,COL make VAL LEARJET COL model VAL 31 COL cert...,COL mfr VAL LEARJET COL model VAL 31,1,0.999985,1,LEARJET 31,LJ31 31,doc8643_description,"[make: LEARJET, model: 31, cert: A10CE]","[mfr: LEARJET, model: 31]"
66,COL make VAL BELLANCA COL model VAL 14 13 COL ...,COL mfr VAL NORTHERN COL model VAL 14 Cruisema...,1,0.999985,1,BELLANCA 14 13,B14A 14 Cruisemaster,doc8643_description,"[make: BELLANCA, model: 14 13, name: CRUISAIR ...","[mfr: NORTHERN, model: 14 Cruisemaster, code: ..."
70,COL make VAL BOEING COL model VAL 737 COL name...,COL mfr VAL BOEING COL model VAL 737-401,1,0.999988,1,BOEING 737,B-737-401,reg,"[make: BOEING, model: 737, name: MAX 8 MAX 9, ...","[mfr: BOEING, model: 737-401]"

In [31]:
matches = matches.sort_values("left_id")

In [32]:
df_agg_cictt = matches.groupby("left_id", as_index=False).agg(count=("left_kv", "count"))

In [33]:
df_agg_cictt = matches.groupby("left_id", as_index=False).agg(
    left_count=("left_kv", "count"),
    right_kv_distinct=("right_kv", lambda s: s.dropna().apply(tuple).nunique()),
)

In [34]:
df_joined = matches.merge(
    df_agg_cictt,
    how="left",
    on=["left_id"],
)

In [35]:
df_joined.head()

,left,right,match,match_confidence,gold,left_id,right_id,source,left_kv,right_kv,left_count,right_kv_distinct
0,COL make VAL AER PEGASO COL model VAL M100 COL...,COL mfr VAL AER-PEGASO COL model VAL M-100S,1,0.999955,1,AER PEGASO M100,AERPEG-M100S-M100S,reg,"[make: AER PEGASO, model: M100, cert: NOT CERT...","[mfr: AER-PEGASO, model: M-100S]",3,3
1,COL make VAL AER PEGASO COL model VAL M100 COL...,COL make VAL AERPEG COL model VAL M100S COL se...,1,0.975039,1,AER PEGASO M100,AERPEG-M100S-M100S,faa,"[make: AER PEGASO, model: M100, cert: NOT CERT...","[make: AERPEG, model: M100S, series: M100S, ce...",3,3
2,COL make VAL AER PEGASO COL model VAL M100 COL...,COL make VAL AER PEGASO COL model VAL M100 COL...,1,0.999964,1,AER PEGASO M100,25,cictt,"[make: AER PEGASO, model: M100, cert: NOT CERT...","[make: AER PEGASO, model: M100, series: S, cer...",3,3
3,COL make VAL AERMACCHI COL model VAL AL60 COL ...,COL mfr VAL MACCHI COL model VAL AL 60,1,0.999988,1,AERMACCHI AL60,AL-60-60,reg,"[make: AERMACCHI, model: AL60, name: SANTA MAR...","[mfr: MACCHI, model: AL 60]",23,23
4,COL make VAL AERMACCHI COL model VAL AL60 COL ...,COL mfr VAL AERMACCHI COL model VAL AL-60 Load...,1,0.999991,1,AERMACCHI AL60,LA60 AL-60 Loadmaster,doc8643_description,"[make: AERMACCHI, model: AL60, name: SANTA MAR...","[mfr: AERMACCHI, model: AL-60 Loadmaster]",23,23

In [36]:

df_joined.to_csv('cictt_agg_repeat_matches.csv', index=False)

In [20]:
df_joined["right_kv"][0][0]

'make: AERPEG'